#!/bin/bash -e
#                                                -*-shell-script-*-
#
# This Docker Hub build hook runs `build.sh`.
#
# Using this build hook is less clumsy than other ways of building
# multiple tags for a single branch update in Docker Hub automated
# builds.
#
# https://docs.docker.com/docker-hub/builds/advanced/

exec ./build.sh $IMAGE_NAME
